/*
 * The Typekit service used to deliver this font or fonts for use on websites
 * is provided by Adobe and is subject to these Terms of Use
 * http://www.adobe.com/products/eulas/tou_typekit. For font license
 * information, see the list below.
 *
 * proxima-nova:
 *   - http://typekit.com/eulas/000000000000000000017829
 *   - http://typekit.com/eulas/000000000000000000017827
 *   - http://typekit.com/eulas/000000000000000000017823
 *
 * © 2009-2016 Adobe Systems Incorporated. All Rights Reserved.
 */
if(!window.Typekit)window.Typekit={};window.Typekit.config={"a":"767520","c":[".tk-proxima-nova","\"proxima-nova\",sans-serif"],"dl":"AAABEgAAAAp1itPYUjWPVuuuJDJrcC5tTD4CxZBuJ1l4/149TZ1ZNgAAsWA=","f":"//use.typekit.net/c/20801b/1w;proxima-nova,2,gbl:W:n4,gbq:W:n6,gbs:W:n7/{format}{/extras*}","fc":[{"id":139,"family":"proxima-nova","src":"{scheme}://{hostname}/af/2b6746/000000000000000000017829/27/{format}{?primer,subset_id,fvd}","descriptors":{"weight":"700","style":"normal","subset_id":2}},{"id":173,"family":"proxima-nova","src":"{scheme}://{hostname}/af/275e5f/000000000000000000017827/27/{format}{?primer,subset_id,fvd}","descriptors":{"weight":"600","style":"normal","subset_id":2}},{"id":175,"family":"proxima-nova","src":"{scheme}://{hostname}/af/6324fc/000000000000000000017823/27/{format}{?primer,subset_id,fvd}","descriptors":{"weight":"400","style":"normal","subset_id":2}}],"fi":[139,173,175],"fn":["proxima-nova",["n4","n6","n7"]],"hn":"use.typekit.net","ht":"tk","js":"1.18.1","kt":"hen3udh","l":"typekit","p":"p.typekit.net","ps":1,"type":"configurable"};
/*{"k":"1.18.1","auto_updating":true,"last_published":"2015-11-03 14:37:48 UTC"}*/
;(function(window,document,undefined){if(!document.querySelector){document.documentElement.className+=" wf-inactive";return;}function aa(a,b,c){return a.call.apply(a.bind,arguments)}function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function h(a,b,c){h=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return h.apply(null,arguments)}var k=Date.now||function(){return+new Date};function ca(){this.P=this.R=this.J=this.L=this.M=!0};function da(a){this.g=a||"-"}da.prototype.b=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.g)};function ea(){var a=[{name:"font-family",value:l.c[n+1]}];this.g=[l.c[n]];this.b=a}function fa(a){for(var b=a.g.join(","),c=[],e=0;e<a.b.length;e++){var d=a.b[e];c.push(d.name+":"+d.value+";")}return b+"{"+c.join("")+"}"};function ga(a,b,c,e){b=a.b.createElement(b);if(c)for(var d in c)c.hasOwnProperty(d)&&("style"==d?b.style.cssText=c[d]:b.setAttribute(d,c[d]));e&&b.appendChild(a.b.createTextNode(e));return b}function ha(a,b,c){a=a.b.getElementsByTagName(b)[0];a||(a=document.documentElement);a.insertBefore(c,a.lastChild)}
function ia(a,b){a.b.body?b():a.b.addEventListener?a.b.addEventListener("DOMContentLoaded",b):a.b.attachEvent("onreadystatechange",function(){"interactive"!=a.b.readyState&&"complete"!=a.b.readyState||b()})}function p(a){a.parentNode&&a.parentNode.removeChild(a)}
function q(a,b,c){b=b||[];c=c||[];for(var e=a.className.split(/\s+/),d=0;d<b.length;d+=1){for(var f=!1,g=0;g<e.length;g+=1)if(b[d]===e[g]){f=!0;break}f||e.push(b[d])}b=[];for(d=0;d<e.length;d+=1){f=!1;for(g=0;g<c.length;g+=1)if(e[d]===c[g]){f=!0;break}f||b.push(e[d])}a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ja(a,b){for(var c=a.className.split(/\s+/),e=0,d=c.length;e<d;e++)if(c[e]==b)return!0;return!1}
function r(a,b){var c=ga(a,"style");c.setAttribute("type","text/css");c.styleSheet?(ha(a,"head",c),c.styleSheet.cssText=b):(c.appendChild(document.createTextNode(b)),ha(a,"head",c))}
function ka(a,b,c){var e=a.b.getElementsByTagName("head")[0];if(e){var d=ga(a,"script",{src:b}),f=!1;d.onload=d.onreadystatechange=function(){f||this.readyState&&"loaded"!=this.readyState&&"complete"!=this.readyState||(f=!0,c&&c(null),d.onload=d.onreadystatechange=null,"HEAD"==d.parentNode.tagName&&e.removeChild(d))};e.appendChild(d);setTimeout(function(){f||(f=!0,c&&c(Error("Script load timeout")))},5E3)}};function la(a,b,c){this.g=a.g.document.documentElement;this.o=b;this.w=c;this.b=new da("-");this.A=!1!==b.events;this.m=!1!==b.classes}function t(a){if(a.m){var b=ja(a.g,a.b.b("wf","active")),c=[],e=[a.b.b("wf","loading")];b||c.push(a.b.b("wf","inactive"));q(a.g,c,e)}v(a,"inactive")}function v(a,b,c){if(a.A&&a.o[b])try{if(c)a.o[b](c.b,w(c));else a.o[b]()}catch(e){console.error('Typekit: Error in "'+b+'" callback',e)}if(a.w[b])if(c)a.w[b](c.b,w(c));else a.w[b]()};function ma(a,b,c){c=c||{};this.b=a;this.g=b;this.weight=c.weight||"400";this.style=c.style||"normal";this.N=c.primer||void 0;this.O=c.subset_id||void 0}function na(a){return("tk-"+a.b).slice(0,26)+"-"+w(a)}function x(a,b){return new ma(b,a.g,{weight:a.weight,style:a.style,N:a.N,O:a.O})}function w(a){return a.style.charAt(0)+a.weight.charAt(0)};function y(a,b){this.g=a;this.m=b;this.b=ga(this.g,"span",{"aria-hidden":"true"},this.m)}function z(a){ha(a.g,"body",a.b)}
function oa(a){return"display:block !important;position:absolute !important;top:-9999px !important;left:-9999px !important;font-size:300px !important;width:auto !important;height:auto !important;line-height:normal !important;margin:0 !important;padding:0 !important;font-variant:normal !important;white-space:nowrap !important;font-family:"+a.b+" !important;font-weight:"+a.weight+" !important;font-style:"+a.style+" !important;"};function pa(a,b,c,e,d,f,g,m){this.I=a;this.U=b;this.B=c;this.b=e;this.D=g||"BESbswy";this.g={};this.V=d||3E3;this.T=m;this.F=f||null;this.A=this.w=this.o=this.m=null;this.m=new y(this.B,this.D);this.o=new y(this.B,this.D);this.w=new y(this.B,this.D);this.A=new y(this.B,this.D);a=this.T?na(this.b):this.b.b;this.m.b.style.cssText=oa(x(this.b,a+",serif"));this.o.b.style.cssText=oa(x(this.b,a+",sans-serif"));this.w.b.style.cssText=oa(x(this.b,"serif"));this.A.b.style.cssText=oa(x(this.b,"sans-serif"));
z(this.m);z(this.o);z(this.w);z(this.A)}var qa={aa:"serif",$:"sans-serif"},ra=null;function sa(){if(null===ra){var a=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(window.navigator.userAgent);ra=!!a&&(536>parseInt(a[1],10)||536===parseInt(a[1],10)&&11>=parseInt(a[2],10))}return ra}pa.prototype.start=function(){this.g.serif=this.w.b.offsetWidth;this.g["sans-serif"]=this.A.b.offsetWidth;this.S=k();ta(this)};
function ua(a,b,c){for(var e in qa)if(qa.hasOwnProperty(e)&&b===a.g[qa[e]]&&c===a.g[qa[e]])return!0;return!1}function ta(a){var b=a.m.b.offsetWidth,c=a.o.b.offsetWidth,e;(e=b===a.g.serif&&c===a.g["sans-serif"])||(e=sa()&&ua(a,b,c));e?k()-a.S>=a.V?sa()&&ua(a,b,c)&&(null===a.F||a.F.hasOwnProperty(a.b.b))?va(a,a.I):va(a,a.U):wa(a):va(a,a.I)}function wa(a){setTimeout(h(function(){ta(this)},a),50)}
function va(a,b){setTimeout(h(function(){p(this.m.b);p(this.o.b);p(this.w.b);p(this.A.b);b(this.b)},a),0)};function xa(a,b,c,e,d,f,g){this.m=a;this.B=b;this.b=e;this.w=c;this.g=d||3E3;this.A=f||void 0;this.o=g}xa.prototype.start=function(){var a=this.w.g.document,b=this,c=k(),e=new Promise(function(d,e){function m(){k()-c>=b.g?e():a.fonts.load(b.b.style+" "+b.b.weight+" 300px "+(b.o?na(b.b):b.b.b),b.A).then(function(a){1<=a.length?d():setTimeout(m,25)},function(){e()})}m()}),d=new Promise(function(a,c){setTimeout(c,b.g)});Promise.race([d,e]).then(function(){b.m(b.b)},function(){b.B(b.b)})};function ya(a,b,c,e){this.D=a;this.b=b;this.g=0;this.A=this.w=!1;this.F=c;this.B=e}var za=null;
function Aa(a,b,c){var e={},d=b.b.length;if(0==d&&c)t(a.b);else{a.g+=d;c&&(a.w=c);var f=[];Ba(b,function(b){var c=a.b;c.m&&q(c.g,[c.b.b("wf",b.b,w(b),"loading")]);v(c,"fontloading",b);c=null;if(null===za)if(window.FontFace){var d=/Gecko.*Firefox\/(\d+)/.exec(window.navigator.userAgent);za=d?42<parseInt(d[1],10):!0}else za=!1;za?c=new xa(h(a.m,a),h(a.o,a),a.D,b,a.F,"BESbswy\ue000\ue001\ue002\ue003\ue004\ue005\ue006",a.B):c=new pa(h(a.m,a),h(a.o,a),a.D,b,a.F,e,"BESbswy\ue000\ue001\ue002\ue003\ue004\ue005\ue006",
a.B);f.push(c)});for(b=0;b<f.length;b++)f[b].start()}}ya.prototype.m=function(a){var b=this.b;b.m&&q(b.g,[b.b.b("wf",a.b,w(a),"active")],[b.b.b("wf",a.b,w(a),"loading"),b.b.b("wf",a.b,w(a),"inactive")]);v(b,"fontactive",a);this.A=!0;Ca(this)};ya.prototype.o=function(a){var b=this.b;if(b.m){var c=ja(b.g,b.b.b("wf",a.b,w(a),"active")),e=[],d=[b.b.b("wf",a.b,w(a),"loading")];c||e.push(b.b.b("wf",a.b,w(a),"inactive"));q(b.g,e,d)}v(b,"fontinactive",a);Ca(this)};
function Ca(a){0==--a.g&&a.w&&(a.A?(a=a.b,a.m&&q(a.g,[a.b.b("wf","active")],[a.b.b("wf","loading"),a.b.b("wf","inactive")]),v(a,"active")):t(a.b))};function Da(a,b){this.o=a;this.g=b;this.b=[]}Da.prototype.m=function(a){this.b.push(a)};Da.prototype.load=function(a,b){var c=a,e=b||{};"string"==typeof c?c=[c]:c&&c.length||(e=c||{},c=[]);if(c.length)for(var d=this,f=c.length,g=0;g<c.length;g++)Ea(this,c[g],function(){0===--f&&Fa(d,e)});else Fa(this,e)};function Ea(a,b,c){b=Ga(a.o,{id:b});ka(a.g,b,c)}
function Fa(a,b){if(0!==a.b.length){for(var c=new la(a.g,b,{}),e=!1,d=0;d<a.b.length;d++)a.b[d].init(),e=e||a.b[d].supportsConfiguredBrowser();if(e)for(c.m&&q(c.g,[c.b.b("wf","loading")]),v(c,"loading"),c=0;c<a.b.length;c++)e=a.b[c],e.supportsConfiguredBrowser()&&e.load(null,c==a.b.length-1,b);else t(c);a.b=[]}};var Ia={Y:"a",ca:"d",X:"i",Z:"j",W:"k",ba:"l",NONE:"x"};function Ja(a){this.b=a}function Ga(a,b){return a.b.replace(/\{([^\{\}]+)\}/g,function(a,e){if("?"==e.charAt(0)){for(var d=e.slice(1).split(","),f=[],g=0;g<d.length;g++)b[d[g]]&&f.push(d[g]+"="+encodeURIComponent(b[d[g]]));return f.length?"?"+f.join("&"):""}return encodeURIComponent(b[e]||"")})};function Ka(){this.b=[]}function La(a,b){for(var c=0;c<b.length;c++)a.b.push(b[c])}function Ba(a,b){for(var c=0;c<a.b.length;c++)b(a.b[c],c,a)}
function Ma(a,b){if("i"===b){var c={},e=new Ka;Ba(a,function(a){c[a.b]||(c[a.b]={});c[a.b][a.weight]||(c[a.b][a.weight]=[]);c[a.b][a.weight].push(a)});for(var d in c){for(var f=[400,300,200,100,500,600,700,800,900],g=0;g<f.length;g++){var m=f[g];if(c[d][m]){La(e,c[d][m]);break}}f=[700,800,900,600,500,400,300,200,100];for(g=0;g<f.length;g++){var u=f[g];if(c[d][u]&&m!==u){La(e,c[d][u]);break}}}Ba(a,function(a){a=x(a,a.b.replace(/(-1|-2)$/,"").slice(0,28)+"-"+w(a));e.b.push(a)});return e}return"x"===
b?new Ka:a}function Na(a,b,c){for(var e=[],d=0;d<b.length;d++){var f=b[d],g=Ga(new Ja(a.g),{scheme:"https",hostname:c,format:f,primer:a.N,subset_id:a.O,fvd:w(a),extension:Oa(f)});"i"===f?e.push("url("+g+")"):e.push("url("+g+') format("'+Pa(f)+'")')}return e.join(",")}
function Qa(a,b,c,e){if("x"===b)return"";var d=[];d.push("font-family:"+(e?na(a):a.b));e="";e="k"===b?Na(a,["l","d","j"],c):Na(a,[b],c);d.push("src:"+e);d.push("font-weight:"+a.weight);d.push("font-style:"+a.style);return"@font-face{"+d.join(";")+";}"}function Pa(a){switch(a){case "d":return"woff";case "i":return"eot";case "l":return"woff2";default:return"opentype"}}function Oa(a){switch(a){case "d":return"woff";case "i":return"eot";case "l":return"woff2";default:return"otf"}}
function Ra(a,b,c,e){var d=[];Ba(a,function(a){d.push(Qa(a,b,c,e))});return d.join("")};function Sa(a){var b=new Image(1,1),c=!1;b.src=a;b.onload=function(){c=!0;b.onload=null};setTimeout(function(){c||(b.src="about:blank",b.onload=null)},3E3)};function A(a,b,c,e,d,f,g){this.b=a;this.C=b;this.H=c;this.G=e;this.v=d;this.u=f;this.K=g}A.prototype.getName=function(){return this.b};function B(a,b,c,e){this.b=null!=a?a:null;this.g=null!=b?b:null;this.m=null!=c?c:null;this.o=null!=e?e:null}var Ta=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;function C(a,b){return a.b>b.b||a.b===b.b&&a.g>b.g||a.b===b.b&&a.g===b.g&&a.m>b.m?1:a.b<b.b||a.b===b.b&&a.g<b.g||a.b===b.b&&a.g===b.g&&a.m<b.m?-1:0}function D(a,b){return-1===C(a,b)}function E(a,b){return 0===C(a,b)||1===C(a,b)}function Ua(a,b){return 0===C(a,b)||-1===C(a,b)}function Va(a,b){return 0===C(a,b)}
B.prototype.toString=function(){return[this.b,this.g||"",this.m||"",this.o||""].join("")};function F(a){a=Ta.exec(a);var b=null,c=null,e=null,d=null;a&&(null!==a[1]&&a[1]&&(b=parseInt(a[1],10)),null!==a[2]&&a[2]&&(c=parseInt(a[2],10)),null!==a[3]&&a[3]&&(e=parseInt(a[3],10)),null!==a[4]&&a[4]&&(/^[0-9]+$/.test(a[4])?d=parseInt(a[4],10):d=a[4]));return new B(b,c,e,d)};function Wa(a){return"Safari"===a.getName()&&"AppleWebKit"===a.H||"Unknown"===a.getName()&&"AppleWebKit"===a.H&&("iPhone"===a.v||"iPad"===a.v||"iPod"===a.v)}function Xa(a){return"Chrome"===a.getName()&&E(a.C,new B(6))&&Ua(a.C,new B(35))}function Ya(a){return"Chrome"===a.getName()&&E(a.C,new B(36))}function Za(a){return"BuiltinBrowser"===a.getName()};function G(a){return"Windows"===a.v}function $a(a){return G(a)&&E(a.u,new B(6,1))}function H(a){return G(a)&&Va(a.u,new B(5,1))||G(a)&&Va(a.u,new B(5,2))||G(a)&&Va(a.u,new B(6,0))||$a(a)}function I(a){return"Macintosh"===a.v&&(E(a.u,new B(10,4))||null===a.u.b)}function ab(a,b){return b.M&&("iPhone"===a.v||"iPod"===a.v)&&E(a.u,new B(4,2))&&D(a.u,new B(5))}function bb(a,b){return b.M&&("iPhone"===a.v||"iPod"===a.v)&&E(a.u,new B(5))}
function cb(a,b){return b.L&&"iPad"===a.v&&E(a.u,new B(4,2))&&D(a.u,new B(5))}function db(a,b){return b.L&&"iPad"===a.v&&E(a.u,new B(5))}function K(a,b){return b.J&&"Android"===a.v}function eb(a,b){return K(a,b)&&E(a.u,new B(2,2))&&D(a.u,new B(3,1))}function fb(a,b){return K(a,b)&&E(a.u,new B(3,1))&&D(a.u,new B(4,1))}function L(a){return"Linux"===a.v||"Ubuntu"===a.v};var gb={a:function(a,b){return"Safari"===a.getName()&&"AppleWebKit"===a.H&&E(a.G,new B(525,13))&&D(a.G,new B(534,50))&&(H(a)||I(a))||Za(a)&&(eb(a,b)||K(a,b)&&E(a.u,new B(4,1)))||b.J&&"Silk"===a.getName()&&D(a.C,new B(2))&&(eb(a,b)||I)||b.J&&"Silk"===a.getName()&&E(a.C,new B(2))&&K(a,b)&&E(a.u,new B(4,1))||Wa(a)&&(cb(a,b)||ab(a,b))||Xa(a)&&(cb(a,b)||ab(a,b))||Ya(a)&&(cb(a,b)||ab(a,b))||"AdobeAIR"===a.getName()&&E(a.C,new B(2,5))&&(G(a)&&null===a.u.b||L(a)||I(a))},d:function(a,b){return Xa(a)&&(H(a)||
L(a)||I(a)||K(a,b)||"CrOS"===a.v||"CrKey"===a.v||db(a,b)||bb(a,b))||Ya(a)&&(db(a,b)||bb(a,b))||"Gecko"===a.H&&1===C(a.G,new B(1,9,1))&&Ua(a.G,new B(38))&&(H(a)||L(a)||I(a)||K(a,b))||"Safari"===a.getName()&&"AppleWebKit"===a.H&&E(a.G,new B(534,50))&&(H(a)||I(a))||Wa(a)&&(db(a,b)||bb(a,b))||"Opera"===a.getName()&&E(a.C,new B(11,10))&&Ua(a.C,new B(22))&&(H(a)||L(a)||I(a)||K(a,b))||"MSIE"===a.getName()&&9<=a.K&&($a(a)||G(a)&&Va(a.u,new B(6,0)))||"Edge"===a.getName()&&$a(a)||"MSIE"===a.getName()&&b.R&&
"Windows Phone"===a.v&&E(a.u,new B(8))||Za(a)&&(b.P&&"BlackBerry"===a.v&&E(a.u,new B(10))||L(a))},j:function(a,b){return Za(a)&&fb(a,b)||b.J&&"Silk"===a.getName()&&E(a.C,new B(2))&&(fb(a,b)||L(a))},i:function(a){return"MSIE"===a.getName()&&E(a.C,new B(6,0))&&(void 0===a.K||9>a.K)&&H(a)},l:function(a,b){return Ya(a)&&(H(a)||L(a)||I(a)||K(a,b)||"CrOS"===a.v||"CrKey"===a.v)||"Gecko"===a.H&&E(a.G,new B(39))&&(H(a)||L(a)||I(a)||K(a,b))||"Opera"===a.getName()&&E(a.C,new B(23))&&(H(a)||L(a)||I(a)||K(a,b))},
x:function(){return!1}};var hb=new A("Unknown",new B,"Unknown",new B,"Unknown",new B,void 0);function M(a){var b=N(a.b,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!==b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=N(a.b,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS|PlayStation|CrKey)/,1);return""!==a?("Mac_PowerPC"==a?a="Macintosh":"PlayStation"==a&&(a="Linux"),a):"Unknown"}
function O(a){var b=N(a.b,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=N(a.b,/Windows Phone( OS)? ([^;)]+)/,2))||(b=N(a.b,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=N(a.b,/(?:Linux|CrOS|CrKey) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=N(a.b,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function ib(){var a=P,b="Unknown",c=F(N(a.b,/Presto\/([\d\w\.]+)/,1)),e=F(O(a)),d=Q(a.g);null!==c.b?b="Presto":(-1!=a.b.indexOf("Gecko")&&(b="Gecko"),c=F(N(a.b,/rv:([^\)]+)/,1)));if(-1!=a.b.indexOf("Opera Mini/")){var f=F(N(a.b,/Opera Mini\/([\d\.]+)/,1));return new A("OperaMini",f,b,c,M(a),e,d)}if(-1!=a.b.indexOf("Version/")&&(f=F(N(a.b,/Version\/([\d\.]+)/,1)),null!==f.b))return new A("Opera",f,b,c,M(a),e,d);f=F(N(a.b,/Opera[\/ ]([\d\.]+)/,1));return null!==f.b?new A("Opera",f,b,c,M(a),e,d):new A("Opera",
new B,b,c,M(a),e,d)}
function jb(){var a=P,b=M(a),c=F(O(a)),e=F(N(a.b,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1)),d="Unknown",f=new B,f="Unknown";/OPR\/[\d.]+/.test(a.b)?d="Opera":-1!=a.b.indexOf("Chrome")||-1!=a.b.indexOf("CrMo")||-1!=a.b.indexOf("CriOS")?d="Chrome":/Silk\/\d/.test(a.b)?d="Silk":"BlackBerry"==b||"Android"==b?d="BuiltinBrowser":-1!=a.b.indexOf("PhantomJS")?d="PhantomJS":-1!=a.b.indexOf("Safari")?d="Safari":-1!=a.b.indexOf("AdobeAIR")?d="AdobeAIR":-1!=a.b.indexOf("PlayStation")&&(d="BuiltinBrowser");"BuiltinBrowser"==
d?f="Unknown":"Silk"==d?f=N(a.b,/Silk\/([\d\._]+)/,1):"Chrome"==d?f=N(a.b,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.b.indexOf("Version/")?f=N(a.b,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==d?f=N(a.b,/AdobeAIR\/([\d\.]+)/,1):"Opera"==d?f=N(a.b,/OPR\/([\d.]+)/,1):"PhantomJS"==d&&(f=N(a.b,/PhantomJS\/([\d.]+)/,1));f=F(f);return new A(d,f,"AppleWebKit",e,b,c,Q(a.g))}function N(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function Q(a){if(a.documentMode)return a.documentMode};function lb(a,b){this.b=b||Array(Math.ceil(a/32));if(!b)for(var c=0;c<this.b.length;c++)this.b[c]=0};function R(a,b){return(a&65535)*b+(((a>>>16)*b&65535)<<16)};function mb(a,b,c){this.b=a;this.m=b;this.g=new lb(a,c)}var nb=[2449897292,4218179547,2675077685,1031960064,1478620578,1386343184,3194259988,2656050674,3012733295,2193273665];
function ob(a,b){if("string"!==typeof b&&"number"!==typeof b)throw Error("Value should be a string or number.");for(var c="number"===typeof b,e=0;e<a.m;e++){var d=0;if(c)var d=nb[e]||0,f=b&4294967295,f=R(f,3432918353),f=f<<15|f>>>17,f=R(f,461845907),d=d^f,d=d<<13|d>>>19,d=R(d,5)+3864292196,d=d^4;else{for(var d=nb[e]||0,g=f=0,m=b.length%4,u=b.length-m,g=0;g<u;g+=4)f=(b.charCodeAt(g+0)&4294967295)<<0|(b.charCodeAt(g+1)&4294967295)<<8|(b.charCodeAt(g+2)&4294967295)<<16|(b.charCodeAt(g+3)&4294967295)<<
24,f=R(f,3432918353),f=f<<15|f>>>17,f=R(f,461845907),d^=f,d=d<<13|d>>>19,d=R(d,5)+3864292196;f=0;switch(m){case 3:f^=(b.charCodeAt(g+2)&4294967295)<<16;case 2:f^=(b.charCodeAt(g+1)&4294967295)<<8;case 1:f^=(b.charCodeAt(g+0)&4294967295)<<0,f=R(f,3432918353),f=f<<15|f>>>17,f=R(f,461845907),d^=f}d^=b.length}d^=d>>>16;d=R(d,2246822507);d^=d>>>13;d=R(d,3266489909);d^=d>>>16;d=(d>>>0)%a.b;f=a.g;if(Math.floor(d/32+1)>f.b.length)throw Error("Index is out of bounds.");g=Math.floor(d/32);if(!(f.b[g]&1<<d-
32*g))return!1}return!0};function pb(){var a;a=qb;if(window.atob)a=window.atob(a);else{a=a.replace(/=+$/,"");if(1==a.length%4)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");for(var b=0,c,e,d=0,f="";e=a.charAt(d++);~e&&(c=b%4?64*c+e:e,b++%4)?f+=String.fromCharCode(255&c>>(-2*b&6)):0)e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e);a=f}c=[];for(b=0;b<a.length;b+=4)c.push(a.charCodeAt(b)<<24|a.charCodeAt(b+1)<<16|a.charCodeAt(b+2)<<8|a.charCodeAt(b+3)<<0);a=c.shift();
b=c.shift();this.b=new mb(a,b,c)}function rb(a,b){if(""===b)return!0;for(var c=b.split(".");0!==c.length;){var e=c.join("."),d="*."+e;if(ob(a.b,e)||ob(a.b,d)||ob(a.b,encodeURIComponent(e))||ob(a.b,encodeURIComponent(d)))return!0;c.shift()}return!1};function sb(a,b){this.b=a;this.g="x";this.A=this.I=null;this.m=[];this.w=b;this.o=this.D=null;this.B=new Ka}sb.prototype.supportsConfiguredBrowser=function(){return"x"!==this.g};sb.prototype.init=function(){if(0<this.m.length){for(var a=[],b=0;b<this.m.length;b++)a.push(fa(this.m[b]));r(this.b,a.join(""))}};
sb.prototype.load=function(a,b,c){var e=this;c=c||{};a=c.timeout;var d=!!c.async,f=Ma(this.B,this.g);c=new la(this.b,c,{active:function(){if(d){var a=Ra(f,e.g,e.w,!1);r(e.b,a)}if(e.F){var a=e.F,b=new Ja("{scheme}://{hostname}/p.gif{?s,k,app,ht,h,f,a,js,_}"),c=(window.__adobewebfontsappname__||a.app||"").toString().substr(0,20),g;g=e.b;g=g.g.location.hostname||g.m.location.hostname;var m=[],S=[];window.Typekit?(window.Typekit.fonts||(window.Typekit.fonts=[]),S=window.Typekit.fonts):window.TypekitPreview&&
(window.TypekitPreview.fonts||(window.TypekitPreview.fonts=[]),S=window.TypekitPreview.fonts);for(var T=0;T<a.b.length;T++){for(var kb=!1,Ha=0;Ha<S.length;Ha++)if(a.b[T]===S[Ha]){kb=!0;break}kb||(m.push(a.b[T]),S.push(a.b[T]))}m.length&&Sa(Ga(b,{scheme:"https",hostname:a.A,s:a.o,k:a.w,app:c,ht:a.m,h:g,f:m.join("."),a:a.g,js:a.version,_:(+new Date).toString()}))}},inactive:function(){if(d){var a=Ra(f,e.g,e.w,!1);r(e.b,a)}}});if(null!==this.o){var g=location.hostname;if(!rb(this.o,g)){console.error('Typekit: the domain "'+
g+'" isn\'t in the list of published domains for kit "'+this.D+'".');t(c);return}}if(f.b.length){g=Ra(f,this.g,this.w,d);r(this.b,g);var m=new ya(this.b,c,a,d);ia(e.b,function(){Aa(m,f,b)})}else t(c)};var tb,P=new function(){var a=document;this.b=navigator.userAgent;this.g=a},ub;
if(-1!=P.b.indexOf("MSIE")||-1!=P.b.indexOf("Trident/")){var U=P,vb=M(U),wb=F(O(U)),xb=null,yb=null,zb=null,Ab=N(U.b,/Trident\/([\d\w\.]+)/,1),Bb=Q(U.g),xb=-1!=U.b.indexOf("MSIE")?F(N(U.b,/MSIE ([\d\w\.]+)/,1)):F(N(U.b,/rv:([\d\w\.]+)/,1));""!==Ab?(yb="Trident",zb=F(Ab)):(yb="Unknown",zb=new B);ub=new A("MSIE",xb,yb,zb,vb,wb,Bb)}else{var Cb;if(-1!=P.b.indexOf("Edge/")){var Db=P,Eb=M(Db),Fb=F(O(Db)),Gb=F(N(Db.b,/Edge\/([\d\w\.]+)/,1));Cb=new A("Edge",Gb,"Edge",Gb,Eb,Fb,Q(Db.g))}else{var Hb;if(-1!=
P.b.indexOf("Opera"))Hb=ib();else{var Ib;if(/OPR\/[\d.]+/.test(P.b))Ib=jb();else{var Jb;if(/AppleWeb(K|k)it/.test(P.b))Jb=jb();else{var Kb;if(-1!=P.b.indexOf("Gecko")){var V=P,Lb="Unknown",Mb=new B,Nb=F(O(V));-1!=V.b.indexOf("Firefox")?(Lb="Firefox",Mb=F(N(V.b,/Firefox\/([\d\w\.]+)/,1))):-1!=V.b.indexOf("Mozilla")&&(Lb="Mozilla");var Ob=F(N(V.b,/rv:([^\)]+)/,1));Kb=new A(Lb,Mb,"Gecko",Ob,M(V),Nb,Q(V.g))}else Kb=hb;Jb=Kb}Ib=Jb}Hb=Ib}Cb=Hb}ub=Cb}tb=ub;
var Pb=new function(){var a=window;this.g=this.m=a;this.b=this.g.document};window.Typekit||(window.Typekit={});if(!window.Typekit.load){var Qb=new Da(new Ja("//"+(window.Typekit.config||{}).hn+"/{id}.js"),Pb);window.Typekit.load=function(){Qb.load.apply(Qb,arguments)};window.Typekit.addKit=function(){Qb.m.apply(Qb,arguments)}}var W,X,l=window.Typekit.config||{};X=new sb(Pb,l.hn);
X.F=new function(){var a=l.ps,b=l.ht,c=l.fi,e=l.a,d=l.kt,f=l.js,g=l.l;this.A=l.p;this.o=a;this.m=b;this.b=c||[];this.g=e||null;this.w=d||null;this.version=f||null;this.app=g||null};W=new ca;W.M=!l.si;W.L=!l.st;W.J=!l.sa;W.R=!l.sw;W.P=!l.sb;X.A=W;if(l.fc)for(var Rb=l.fc,Y=0;Y<Rb.length;Y++)X.B.b.push(new ma(Rb[Y].family,Rb[Y].src,Rb[Y].descriptors));if(l.dl){var qb=l.dl;try{X.o=new pb}catch(a){}}l.kt&&(X.D=l.kt);if(l.c)for(var n=0;n<l.c.length;n+=2)X.m.push(new ea);X.I=tb;var Sb;
a:{var Tb=X.I,Ub=new ca,Vb=X.A||Ub,Wb;for(Wb in Ia){var Z=Ia[Wb];if(gb[Z]&&gb[Z](Tb,Vb)){Sb=Z;break a}}for(Wb in Ia)if(Z=Ia[Wb],gb[Z]&&gb[Z](Tb,Ub)){Sb="x";break a}Sb="k"}X.g=Sb;window.Typekit.addKit(X);
if(1===Math.round(30*Math.random())){var Xb=window.Typekit.load,Yb=[];window.Typekit.load=function(a){a=a||{};var b=a.active||function(){},c=a.fontactive||function(){},e=(new Date).getTime();a.active=function(){b();var a=JSON.stringify({fonts:Yb,augmentations:[],font_loading:window.FontFace?"native":"non-native",active_duration:(new Date).getTime()-e,javascript_version:l.js,kit_type:"configurable"});if(!window.XDomainRequest){var c=new XMLHttpRequest;c.open("POST","https://performance.typekit.net/");
c.send(a)}};a.fontactive=function(a,b){var g,m;c(a,b);a:{g=b.charAt(0);m=b.charAt(1);/[1-9]/.test(m)||(m=4);g="i"===g?"italic":"o"===g?"oblique":"normal";m=m+"00";for(var u=l.fc,J=0;J<u.length;J++)if(u[J].family===a&&u[J].descriptors.weight===m&&u[J].descriptors.style===g){g=u[J].id;break a}g=0}Yb.push({id:g,duration:(new Date).getTime()-e,dynamic:!1})};Xb(a)}}if(window.WebFont)try{window.Typekit.load()}catch(a){};}(this,document));

